sky:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    host: localhost
    port: 1433
    database: sky_take_out
    username: sa
    password: 123456yoss
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tA5PArkkcHWcVC7SRg5
    access-key-secret: emb8b6Q1OrbgYUASHpziQUjOTRaD8U
    bucket-name: ylnx-sky-take-out